main:
  host: https://weather.visualcrossing.com
  api_key: <YOUR_API_KEY>
  countries:
    - country: PL
      city: lodz
    - country: DK
      city: copenhagen
    - country: PK
      city: islamabad
    - country: BE
      city: brussels